name: addons-release

on:
  release:
    types: [published]
    tags:
      - v*
  push:
    branches:
      - master
      - r*
  pull_request:
    branches:
      - master
      - r*
  schedule:
    - cron:  '0 0 * * *'

env:
  BAZEL_VERSION: 1.1.0

jobs:
  manylinux-cpu-release-test:
    name: Test release on Ubuntu
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Release test Ubuntu
        run: |
          set -x -e
          bash tools/run_cpu_tests.sh
  manylinux-release-wheel:
    name: Build release wheels for manylinux2010
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: ['3.5', '3.6', '3.7']
    steps:
      - if: github.event_name == 'schedule'
        run: echo "::set-env name=NIGHTLY_FLAG::--nightly"
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build manylinux2010 wheels
        if: github.event_name == 'schedule' || github.event_name == 'release' || matrix.python-version == '3.5'
        env:
          PY_VERSION: ${{ matrix.python-version }}
        run: bash .github/workflows/make_wheel_Linux.sh
      - uses: actions/upload-artifact@v1
        if: github.event_name == 'schedule' || github.event_name == 'release' || matrix.python-version == '3.5'
        with:
          name: ${{ runner.os }}-wheels
          path: wheelhouse

  macos-release-wheel:
    name: Build release wheels for macOS
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ['3.5', '3.6', '3.7']
    steps:
      - if: github.event_name == 'schedule'
        run: echo "::set-env name=NIGHTLY_FLAG::--nightly"
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build macOS wheels
        if: github.event_name == 'schedule' || github.event_name == 'release' || matrix.python-version == '3.5'
        run: bash .github/workflows/make_wheel_Windows.sh
      - uses: actions/upload-artifact@v1
        if: github.event_name == 'schedule' || github.event_name == 'release' || matrix.python-version == '3.5'
        with:
          name: ${{ runner.os }}-wheels
          path: wheelhouse

  windows-release-wheel:
    name: Build release wheels for Windows
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.5', '3.6', '3.7']
    steps:
      - if: github.event_name == 'schedule'
        run: echo "::set-env name=NIGHTLY_FLAG::--nightly"
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build Windows wheels
        env:
          TF_NEED_CUDA: 0
          BAZEL_VC: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/"
        shell: bash
        if: github.event_name == 'schedule' || github.event_name == 'release' || matrix.python-version == '3.5'
        run: bash .github/workflows/make_wheel_Windows.sh
      - uses: actions/upload-artifact@v1
        if: github.event_name == 'schedule' || github.event_name == 'release' || matrix.python-version == '3.5'
        with:
          name: ${{ runner.os }}-wheels
          path: wheelhouse

  upload-wheels:
    name: Publish wheels to PyPi
    needs: [manylinux-release-wheel, macos-release-wheel, windows-release-wheel, manylinux-cpu-release-test]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: Linux-wheels
          path: Linux-wheels
      - uses: actions/download-artifact@v1
        with:
          name: macOS-wheels
          path: macOS-wheels
      - uses: actions/download-artifact@v1
        with:
          name: Windows-wheels
          path: Windows-wheels
      - run: |
          set -e -x
          mkdir -p dist
          cp Linux-wheels/*.whl dist/
          cp macOS-wheels/*.whl dist/
          cp Windows-wheels/*.whl dist/
          ls -la dist/
          sha256sum dist/*.whl
      - uses: pypa/gh-action-pypi-publish@master
        if: github.event_name == 'schedule' || github.event_name == 'release'
        with:
          user: __token__
          password: ${{ secrets.pypi_token }}
